### ISSUE TITLE
Sumotorrents not starting downloads

### ISSUE THREAD

**Issue by kangarooo** [ngosang/qBittorrent-plugins#2]
Added plugin and search works, but cant download anything double clicking- results from sumotorrent doesnt start up, doesnt show up in qbitorrent.

**Comment by ngosang** [comment]
Sumotorrent has changed the website so I can't retrieve the download link properly.

**Comment by nathan323** [comment]
So this kills the plugin indefinitely?

**Comment by ngosang** [comment]
@kangarooo @nathan323 plugin updated. It's working again.
https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins

**Comment by kangarooo** [comment]
For torrents that download works, they dont download. For torrents that download dont work, then works manually opening description page and then copying magnet link.

**Comment by ngosang** [comment]
> For torrents that download dont work, then works manually opening description page and then copying magnet link.

@kangarooo could yo give me an example?
