### ISSUE TITLE
Cannot install sumotorrent plugin - "Plugin is not supported"

### ISSUE THREAD

**Issue by AnthonyBe** [ngosang/qBittorrent-plugins#5]
I've been trying to install the new SumoTorrent v1.4 script and I get an error:

`Couldn't install "sumotorrent" search engine plugin. Plugin is not supported.`

I'm using qB 4.0.4 64-bit on Win10

**Comment by AnthonyBe** [comment]
[sumotorrent.py.txt](https://github.com/ngosang/qBittorrent-plugins/files/1976269/sumotorrent.py.txt)

I ran the current Python3 only SumoTorrent script through the pasteurize script (part of python Future - python-future.org) to take the python 3 functions and backport to Python 2 compatible.

The attached version of the script is the result, which installed fine for me and seems to work fine on my system which is running Windows 10, Python 2.7.15, and qB 4.0.4 x64.

**Comment by ngosang** [comment]
@AnthonyBe plugin updated. It's working again.
https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins
